HTTP_LINE_TERMINATOR = b"\r\n"

HTTP_VERSION = "HTTP/1.1"
PATH_QUERY_SEPARATOR = "?"
QUERY_ELEMENTS_SEPARATOR = "&"
QUERY_ELEMENT_KEY_VALUE_SEPARATOR = "="

CONNECTION_HEADER = "connection"
CONTENT_TYPE_HEADER = "content-type"
CONTENT_LENGTH_HEADER = "content-length"
LOCATION_HEADER = "location"

CONNECTION_HEADER_CLOSE = "close"
CONTENT_TYPE_HEADER_JSON = "application/json"
CONTENT_TYPE_HEADER_HTML = "text/html; charset=utf-8"
