OAUTH_AUTH_CODE_GRANT_TYPE = "authorization_code"
OAUTH_AUTH_CODE_RESPONSE_TYPE = "code"
OAUTH_BEARER_TOKEN_TYPE = "Bearer"
OAUTH_READ_SCOPE = "read"

TOKEN_EXCHANGE_SERVER_HOST = "127.0.0.1"
TOKEN_EXCHANGE_SERVER_PORT = 45678

STEPIK_AUTHORIZATION_ENDPOINT = "https://stepik.org/oauth2/authorize/"
STEPIK_TOKEN_ENDPOINT = "https://stepik.org/oauth2/token/"
STEPIK_OAUTH_APP_CLIENT_ID = "X2RZBLIMNv1ZvNgI5vblb9jeRC8glC0s2tbdI4uP"
STEPIK_OATH_REDIRECT_URI = (
    f"http://{TOKEN_EXCHANGE_SERVER_HOST}:{TOKEN_EXCHANGE_SERVER_PORT}/auth"
)
